import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import User from '@/models/User';
import Vehicle from '@/models/Vehicle';
import Driver from '@/models/Driver';
import Trip from '@/models/Trip';
import MaintenanceLog from '@/models/MaintenanceLog';
import FuelLog from '@/models/FuelLog';
import Alert from '@/models/Alert';
import bcrypt from 'bcryptjs';

export const dynamic = 'force-dynamic';

export async function GET() {
    try {
        await dbConnect();

        // 1. Clear all existing data
        await Promise.all([
            User.deleteMany({}),
            Vehicle.deleteMany({}),
            Driver.deleteMany({}),
            Trip.deleteMany({}),
            MaintenanceLog.deleteMany({}),
            FuelLog.deleteMany({}),
            Alert.deleteMany({}),
        ]);

        // 2. Create Users
        const users = await User.insertMany([
            {
                name: 'Rajesh Kumar',
                email: 'admin@fleetflow.com',
                password: await bcrypt.hash('Admin@123', 12),
                role: 'fleet_manager',
                isActive: true,
            },
            {
                name: 'Priya Sharma',
                email: 'dispatch@fleetflow.com',
                password: await bcrypt.hash('Dispatch@123', 12),
                role: 'dispatcher',
                isActive: true,
            },
            {
                name: 'Suresh Patel',
                email: 'safety@fleetflow.com',
                password: await bcrypt.hash('Safety@123', 12),
                role: 'safety_officer',
                isActive: true,
            },
            {
                name: 'Meena Iyer',
                email: 'finance@fleetflow.com',
                password: await bcrypt.hash('Finance@123', 12),
                role: 'financial_analyst',
                isActive: true,
            },
        ]);

        // 3. Create Vehicles
        const vehicles = await Vehicle.insertMany([
            {
                name: 'Tata Ace Gold',
                model: 'Ace Gold 2022',
                licensePlate: 'MH12AB1234',
                type: 'Truck',
                maxCapacity: 750,
                currentOdometer: 48200,
                lastServiceOdometer: 45000,
                acquisitionCost: 850000,
                region: 'West',
                status: 'Available',
                yearOfManufacture: 2022,
                averageFuelCostPerKm: 4.2,
                monthlyBudget: 8000,
                notes: 'Primary Mumbai delivery truck',
                lastTripDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
            },
            {
                name: 'Mahindra Bolero Pikup',
                model: 'Bolero Pikup 2021',
                licensePlate: 'DL8CAF5678',
                type: 'Truck',
                maxCapacity: 1200,
                currentOdometer: 92400,
                lastServiceOdometer: 90000,
                acquisitionCost: 1100000,
                region: 'North',
                status: 'On Trip',
                yearOfManufacture: 2021,
                averageFuelCostPerKm: 5.1,
                monthlyBudget: 12000,
                notes: 'Delhi NCR long-haul truck',
                lastTripDate: new Date(),
            },
            {
                name: 'Ashok Leyland Dost',
                model: 'Dost Strong 2023',
                licensePlate: 'KA03MN9012',
                type: 'Truck',
                maxCapacity: 1500,
                currentOdometer: 31500,
                lastServiceOdometer: 30000,
                acquisitionCost: 1450000,
                region: 'South',
                status: 'In Shop',
                yearOfManufacture: 2023,
                averageFuelCostPerKm: 4.8,
                monthlyBudget: 10000,
                notes: 'Bangalore warehouse truck — engine servicing',
                lastTripDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
            },
            {
                name: 'Force Traveller Van',
                model: 'Traveller 3350 2022',
                licensePlate: 'GJ05TK3456',
                type: 'Van',
                maxCapacity: 500,
                currentOdometer: 67800,
                lastServiceOdometer: 65000,
                acquisitionCost: 780000,
                region: 'West',
                status: 'Available',
                yearOfManufacture: 2022,
                averageFuelCostPerKm: 3.6,
                monthlyBudget: 7000,
                notes: 'Ahmedabad city deliveries',
                lastTripDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
            },
            {
                name: 'Maruti Eeco Cargo',
                model: 'Eeco Cargo CNG 2023',
                licensePlate: 'TN09XZ7890',
                type: 'Van',
                maxCapacity: 400,
                currentOdometer: 18900,
                lastServiceOdometer: 18000,
                acquisitionCost: 620000,
                region: 'South',
                status: 'On Trip',
                yearOfManufacture: 2023,
                averageFuelCostPerKm: 2.4,
                monthlyBudget: 5000,
                notes: 'Chennai city CNG van — low operating cost',
                lastTripDate: new Date(),
            },
            {
                name: 'Tata Winger Van',
                model: 'Winger Cargo 2021',
                licensePlate: 'WB24CD2345',
                type: 'Van',
                maxCapacity: 600,
                currentOdometer: 54300,
                lastServiceOdometer: 50000,
                acquisitionCost: 720000,
                region: 'East',
                status: 'Available',
                yearOfManufacture: 2021,
                averageFuelCostPerKm: 3.9,
                monthlyBudget: 7500,
                notes: 'Kolkata distribution van',
                lastTripDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
            },
            {
                name: 'Hero Splendor Cargo',
                model: 'Splendor+ 2023',
                licensePlate: 'MH01AK6789',
                type: 'Bike',
                maxCapacity: 30,
                currentOdometer: 12400,
                lastServiceOdometer: 10000,
                acquisitionCost: 85000,
                region: 'West',
                status: 'Available',
                yearOfManufacture: 2023,
                averageFuelCostPerKm: 1.2,
                monthlyBudget: 1500,
                notes: 'Mumbai last-mile delivery bike',
                lastTripDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
            },
            {
                name: 'Bajaj RE Compact',
                model: 'RE Compact CNG 2022',
                licensePlate: 'RJ14PQ4567',
                type: 'Bike',
                maxCapacity: 25,
                currentOdometer: 29800,
                lastServiceOdometer: 25000,
                acquisitionCost: 195000,
                region: 'North',
                status: 'Available',
                yearOfManufacture: 2022,
                averageFuelCostPerKm: 1.0,
                monthlyBudget: 2000,
                notes: 'Jaipur local delivery — CNG auto',
                lastTripDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
            },
            {
                name: 'Tata 407 Gold',
                model: '407 Gold EX2 2020',
                licensePlate: 'AP28EF8901',
                type: 'Truck',
                maxCapacity: 3000,
                currentOdometer: 183000,
                lastServiceOdometer: 178000,
                acquisitionCost: 1850000,
                region: 'South',
                status: 'Available',
                yearOfManufacture: 2020,
                averageFuelCostPerKm: 6.5,
                monthlyBudget: 15000,
                notes: 'Hyderabad heavy goods truck — aging fleet',
                lastTripDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
            },
            {
                name: 'Piaggio Ape City',
                model: 'Ape City Plus 2023',
                licensePlate: 'PB10GH2678',
                type: 'Bike',
                maxCapacity: 20,
                currentOdometer: 8700,
                lastServiceOdometer: 5000,
                acquisitionCost: 175000,
                region: 'North',
                status: 'Retired',
                yearOfManufacture: 2019,
                averageFuelCostPerKm: 1.5,
                monthlyBudget: 1000,
                notes: 'Ludhiana — retired after accident damage',
                lastTripDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
            },
        ]);

        // 4. Create Drivers
        const drivers = await Driver.insertMany([
            {
                name: 'Vikram Singh',
                email: 'vikram.singh@fleetflow.com',
                phone: '9876543210',
                licenseNumber: 'MH0120180012345',
                licenseExpiry: new Date('2027-06-15'),
                licenseCategory: ['Truck', 'Van'],
                status: 'On Duty',
                safetyScore: 92,
                totalTrips: 148,
                completedTrips: 142,
                cancelledTrips: 6,
                totalHoursToday: 4.5,
                lastDutyDate: new Date(),
                incidents: [],
            },
            {
                name: 'Ravi Verma',
                email: 'ravi.verma@fleetflow.com',
                phone: '9765432109',
                licenseNumber: 'DL0420190023456',
                licenseExpiry: new Date('2026-03-20'),
                licenseCategory: ['Truck'],
                status: 'On Duty',
                safetyScore: 85,
                totalTrips: 203,
                completedTrips: 188,
                cancelledTrips: 15,
                totalHoursToday: 6.0,
                lastDutyDate: new Date(),
                incidents: [
                    { date: new Date('2025-08-10'), description: 'Minor scrape on loading dock', severity: 'Low' },
                ],
            },
            {
                name: 'Anand Krishnan',
                email: 'anand.krishnan@fleetflow.com',
                phone: '9654321098',
                licenseNumber: 'KA0520200034567',
                licenseExpiry: new Date('2028-11-30'),
                licenseCategory: ['Van', 'Bike'],
                status: 'Off Duty',
                safetyScore: 97,
                totalTrips: 89,
                completedTrips: 88,
                cancelledTrips: 1,
                totalHoursToday: 0,
                lastDutyDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
                incidents: [],
            },
            {
                name: 'Deepak Yadav',
                email: 'deepak.yadav@fleetflow.com',
                phone: '9543210987',
                licenseNumber: 'GJ0620170045678',
                licenseExpiry: new Date('2025-03-10'),
                licenseCategory: ['Truck', 'Van'],
                status: 'Suspended',
                safetyScore: 61,
                totalTrips: 312,
                completedTrips: 278,
                cancelledTrips: 34,
                totalHoursToday: 0,
                lastDutyDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
                incidents: [
                    { date: new Date('2024-12-05'), description: 'Ran red light at Sarkhej crossing', severity: 'High' },
                    { date: new Date('2025-01-18'), description: 'Late delivery — cargo delay', severity: 'Low' },
                    { date: new Date('2025-02-20'), description: 'Minor collision at warehouse gate', severity: 'Medium' },
                ],
            },
            {
                name: 'Sunil Mishra',
                email: 'sunil.mishra@fleetflow.com',
                phone: '9432109876',
                licenseNumber: 'TN0920210056789',
                licenseExpiry: new Date('2026-02-28'),
                licenseCategory: ['Van'],
                status: 'Off Duty',
                safetyScore: 78,
                totalTrips: 67,
                completedTrips: 61,
                cancelledTrips: 6,
                totalHoursToday: 0,
                lastDutyDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
                incidents: [
                    { date: new Date('2025-09-14'), description: 'Cargo damage due to improper loading', severity: 'Medium' },
                ],
            },
            {
                name: 'Amit Joshi',
                email: 'amit.joshi@fleetflow.com',
                phone: '9321098765',
                licenseNumber: 'WB1120220067890',
                licenseExpiry: new Date('2029-07-22'),
                licenseCategory: ['Truck', 'Van', 'Bike'],
                status: 'Off Duty',
                safetyScore: 100,
                totalTrips: 34,
                completedTrips: 34,
                cancelledTrips: 0,
                totalHoursToday: 0,
                lastDutyDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
                incidents: [],
            },
            {
                name: 'Mohan Lal',
                email: 'mohan.lal@fleetflow.com',
                phone: '9210987654',
                licenseNumber: 'RJ1420190078901',
                licenseExpiry: new Date('2026-04-10'),
                licenseCategory: ['Bike'],
                status: 'Off Duty',
                safetyScore: 88,
                totalTrips: 421,
                completedTrips: 398,
                cancelledTrips: 23,
                totalHoursToday: 0,
                lastDutyDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
                incidents: [
                    { date: new Date('2025-05-03'), description: 'Speeding on NH48', severity: 'Medium' },
                ],
            },
            {
                name: 'Pooja Nair',
                email: 'pooja.nair@fleetflow.com',
                phone: '9109876543',
                licenseNumber: 'AP0220230089012',
                licenseExpiry: new Date('2030-01-15'),
                licenseCategory: ['Van', 'Bike'],
                status: 'Off Duty',
                safetyScore: 95,
                totalTrips: 22,
                completedTrips: 21,
                cancelledTrips: 1,
                totalHoursToday: 0,
                lastDutyDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
                incidents: [],
            },
        ]);

        // 5. Create Trips
        const trips = await Trip.insertMany([
            // COMPLETED trips
            {
                vehicle: vehicles[0]._id,
                driver: drivers[2]._id,
                origin: 'Bhiwandi Warehouse, Mumbai',
                destination: 'Dadar Market, Mumbai',
                cargoDescription: 'FMCG goods — Patanjali products',
                cargoWeight: 520,
                estimatedDistanceKm: 45,
                actualDistanceKm: 48,
                status: 'Completed',
                startOdometer: 48000,
                endOdometer: 48048,
                revenue: 3200,
                notes: 'Smooth delivery. Unloading took 45 mins.',
                startTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 4 * 60 * 60 * 1000),
                endTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[3]._id,
                driver: drivers[2]._id,
                origin: 'GIDC Vatva, Ahmedabad',
                destination: 'Manek Chowk, Ahmedabad',
                cargoDescription: 'Textile rolls — Surat fabric',
                cargoWeight: 380,
                estimatedDistanceKm: 22,
                actualDistanceKm: 24,
                status: 'Completed',
                startOdometer: 67650,
                endOdometer: 67674,
                revenue: 1800,
                notes: 'Delivery completed on time.',
                startTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000),
                endTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 4 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[5]._id,
                driver: drivers[5]._id,
                origin: 'Howrah Industrial Area, Kolkata',
                destination: 'New Market, Kolkata',
                cargoDescription: 'Electronics — mobile accessories',
                cargoWeight: 290,
                estimatedDistanceKm: 18,
                actualDistanceKm: 19,
                status: 'Completed',
                startOdometer: 54200,
                endOdometer: 54219,
                revenue: 1500,
                notes: 'All items intact. Customer satisfied.',
                startTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000),
                endTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[8]._id,
                driver: drivers[7]._id,
                origin: 'Uppal Industrial Area, Hyderabad',
                destination: 'Secunderabad Railway Yard',
                cargoDescription: 'Steel pipes and hardware',
                cargoWeight: 2400,
                estimatedDistanceKm: 35,
                actualDistanceKm: 37,
                status: 'Completed',
                startOdometer: 182800,
                endOdometer: 182837,
                revenue: 8500,
                notes: 'Heavy load — required extra strapping.',
                startTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000),
                endTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[6]._id,
                driver: drivers[6]._id,
                origin: 'Kurla East, Mumbai',
                destination: 'Andheri West, Mumbai',
                cargoDescription: 'Documents + small parcels — courier',
                cargoWeight: 18,
                estimatedDistanceKm: 14,
                actualDistanceKm: 15,
                status: 'Completed',
                startOdometer: 12280,
                endOdometer: 12295,
                revenue: 450,
                notes: 'Express delivery completed in time.',
                startTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000),
                endTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[0]._id,
                driver: drivers[0]._id,
                origin: 'Vashi APMC, Navi Mumbai',
                destination: 'Crawford Market, Mumbai',
                cargoDescription: 'Fresh vegetables and fruits',
                cargoWeight: 600,
                estimatedDistanceKm: 32,
                actualDistanceKm: 34,
                status: 'Completed',
                startOdometer: 47900,
                endOdometer: 47934,
                revenue: 2800,
                notes: 'Early morning delivery — market opens at 6AM.',
                startTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000),
                endTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 - 7 * 60 * 60 * 1000),
            },

            // DISPATCHED trips
            {
                vehicle: vehicles[1]._id,
                driver: drivers[1]._id,
                origin: 'Okhla Industrial Estate, Delhi',
                destination: 'Meerut Goods Naka, UP',
                cargoDescription: 'Pharmaceutical supplies — medicines',
                cargoWeight: 950,
                estimatedDistanceKm: 85,
                status: 'Dispatched',
                startOdometer: 92250,
                revenue: 0,
                startTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[4]._id,
                driver: drivers[0]._id,
                origin: 'Ambattur Industrial Estate, Chennai',
                destination: 'T Nagar Shopping District, Chennai',
                cargoDescription: 'Garments — branded apparel boxes',
                cargoWeight: 320,
                estimatedDistanceKm: 28,
                status: 'Dispatched',
                startOdometer: 18800,
                revenue: 0,
                startTime: new Date(Date.now() - 1 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
            },

            // DRAFT trips
            {
                vehicle: vehicles[3]._id,
                driver: drivers[2]._id,
                origin: 'Sachin GIDC, Surat',
                destination: 'Ring Road Market, Surat',
                cargoDescription: 'Synthetic fabric rolls',
                cargoWeight: 420,
                estimatedDistanceKm: 30,
                status: 'Draft',
                revenue: 0,
                createdAt: new Date(Date.now() - 30 * 60 * 1000),
            },
            {
                vehicle: vehicles[6]._id,
                driver: drivers[6]._id,
                origin: 'Dharavi, Mumbai',
                destination: 'BKC Commercial Hub, Mumbai',
                cargoDescription: 'Office stationery + courier packets',
                cargoWeight: 22,
                estimatedDistanceKm: 10,
                status: 'Draft',
                revenue: 0,
                createdAt: new Date(Date.now() - 15 * 60 * 1000),
            },

            // CANCELLED trips
            {
                vehicle: vehicles[5]._id,
                driver: drivers[4]._id,
                origin: 'Kalyani Industrial Park, WB',
                destination: 'Siliguri Wholesale Market',
                cargoDescription: 'Consumer electronics',
                cargoWeight: 550,
                estimatedDistanceKm: 600,
                status: 'Cancelled',
                cancellationReason: 'Vehicle Breakdown',
                cancellationNote: 'Engine overheating — sent for emergency service.',
                revenue: 0,
                startTime: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
                createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000 - 1 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[2]._id,
                driver: drivers[3]._id,
                origin: 'Peenya Industrial Area, Bangalore',
                destination: 'Marathahalli Tech Park, Bangalore',
                cargoDescription: 'IT hardware — servers and networking gear',
                cargoWeight: 800,
                estimatedDistanceKm: 22,
                status: 'Cancelled',
                cancellationReason: 'Driver Unavailable',
                cancellationNote: 'Driver license expired — assignment blocked by system.',
                revenue: 0,
                createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
            },
        ]);

        // 6. Create Maintenance Logs
        const maintenanceLogs = await MaintenanceLog.insertMany([
            // ONGOING
            {
                vehicle: vehicles[2]._id,
                type: 'Engine Repair',
                cost: 18500,
                description: 'Engine oil leak and overheating issue. Cylinder head gasket replacement required.',
                serviceProvider: 'Ashok Leyland Authorised Service, Peenya, Bangalore',
                status: 'Ongoing',
                serviceDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
                odometerAtService: 31500,
            },
            {
                vehicle: vehicles[7]._id,
                type: 'Brake Service',
                cost: 4200,
                description: 'Brake pads worn out. Front brake disc replacement + rear drum adjustment.',
                serviceProvider: 'Bajaj Service Centre, Jaipur',
                status: 'Ongoing',
                serviceDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
                odometerAtService: 29800,
            },
            // RESOLVED
            {
                vehicle: vehicles[0]._id,
                type: 'Oil Change',
                cost: 2800,
                description: 'Routine oil change + air filter replacement at 45000 km service.',
                serviceProvider: 'Tata Motors Service, Thane',
                status: 'Resolved',
                serviceDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000),
                resolvedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000),
                odometerAtService: 45000,
            },
            {
                vehicle: vehicles[3]._id,
                type: 'Tire Replacement',
                cost: 9600,
                description: 'All 4 tyres replaced. Installed MRF Wanderer tyres.',
                serviceProvider: 'MRF Tyre Point, Ahmedabad',
                status: 'Resolved',
                serviceDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
                resolvedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000),
                odometerAtService: 64000,
            },
            {
                vehicle: vehicles[8]._id,
                type: 'Battery',
                cost: 7500,
                description: 'Original battery dead. Replaced with Amaron 85Ah battery.',
                serviceProvider: 'Amaron Battery Centre, Hyderabad',
                status: 'Resolved',
                serviceDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
                resolvedAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000),
                odometerAtService: 181000,
            },
            {
                vehicle: vehicles[5]._id,
                type: 'Other',
                cost: 3200,
                description: 'AC not cooling. Refrigerant top-up and compressor belt replaced.',
                serviceProvider: 'Cool Car AC Service, Kolkata',
                status: 'Resolved',
                serviceDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
                resolvedAt: new Date(Date.now() - 44 * 24 * 60 * 60 * 1000),
                odometerAtService: 52000,
            },
        ]);

        // 7. Create Fuel Logs (use save() individually to trigger pre-save hooks)
        const fuelLogData = [
            {
                vehicle: vehicles[0]._id,
                trip: trips[0]._id,
                liters: 4.8,
                costPerLiter: 106.72,
                totalCost: 512.26,
                kmDriven: 48,
                fuelEfficiency: 10.0,
                date: trips[0].endTime,
            },
            {
                vehicle: vehicles[3]._id,
                trip: trips[1]._id,
                liters: 2.4,
                costPerLiter: 93.02,
                totalCost: 223.25,
                kmDriven: 24,
                fuelEfficiency: 10.0,
                date: trips[1].endTime,
            },
            {
                vehicle: vehicles[5]._id,
                trip: trips[2]._id,
                liters: 2.1,
                costPerLiter: 103.94,
                totalCost: 218.27,
                kmDriven: 19,
                fuelEfficiency: 9.05,
                date: trips[2].endTime,
            },
            {
                vehicle: vehicles[8]._id,
                trip: trips[3]._id,
                liters: 5.9,
                costPerLiter: 102.17,
                totalCost: 602.80,
                kmDriven: 37,
                fuelEfficiency: 6.27,
                date: trips[3].endTime,
            },
            {
                vehicle: vehicles[6]._id,
                trip: trips[4]._id,
                liters: 1.2,
                costPerLiter: 104.50,
                totalCost: 125.40,
                kmDriven: 15,
                fuelEfficiency: 12.50,
                date: trips[4].endTime,
            },
            {
                vehicle: vehicles[0]._id,
                trip: trips[5]._id,
                liters: 3.6,
                costPerLiter: 106.72,
                totalCost: 384.19,
                kmDriven: 34,
                fuelEfficiency: 9.44,
                date: trips[5].endTime,
            },
            {
                vehicle: vehicles[1]._id,
                liters: 40,
                costPerLiter: 96.72,
                totalCost: 3868.80,
                kmDriven: 380,
                fuelEfficiency: 9.5,
                date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
            },
            {
                vehicle: vehicles[2]._id,
                liters: 18,
                costPerLiter: 94.25,
                totalCost: 1696.50,
                kmDriven: 160,
                fuelEfficiency: 8.89,
                date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
            },
        ];

        const fuelLogs = await FuelLog.insertMany(fuelLogData);

        // 8. Create Alerts
        const alerts = await Alert.insertMany([
            {
                type: 'License Expiring',
                severity: 'Critical',
                message: "Sunil Mishra's driving license expires in 7 days (28 Feb 2026). Immediate renewal required.",
                driver: drivers[4]._id,
                isRead: false,
                isDismissed: false,
                createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
            },
            {
                type: 'License Expiring',
                severity: 'Medium',
                message: "Mohan Lal's driving license expires in 48 days (10 Apr 2026). Please renew soon.",
                driver: drivers[6]._id,
                isRead: false,
                isDismissed: false,
                createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
            },
            {
                type: 'Service Due',
                severity: 'High',
                message: 'Tata Ace Gold (MH12AB1234) is approaching 5000km service interval. Current gap: 3200km.',
                vehicle: vehicles[0]._id,
                isRead: false,
                isDismissed: false,
                createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
            },
            {
                type: 'Service Due',
                severity: 'High',
                message: 'Tata 407 Gold (AP28EF8901) is overdue for service. Gap: 5000km since last service.',
                vehicle: vehicles[8]._id,
                isRead: false,
                isDismissed: false,
                createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
            },
            {
                type: 'Idle Vehicle',
                severity: 'Low',
                message: 'Bajaj RE Compact (RJ14PQ4567) has been idle for 9 days with no trips assigned.',
                vehicle: vehicles[7]._id,
                isRead: true,
                isDismissed: false,
                createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
            },
            {
                type: 'Budget Exceeded',
                severity: 'Medium',
                message: 'Tata 407 Gold (AP28EF8901) has exceeded its monthly maintenance budget of ₹15,000.',
                vehicle: vehicles[8]._id,
                isRead: true,
                isDismissed: false,
                createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
            },
        ]);

        // 9. Return success response
        return NextResponse.json({
            success: true,
            message: 'Database seeded successfully',
            counts: {
                users: users.length,
                vehicles: vehicles.length,
                drivers: drivers.length,
                trips: trips.length,
                maintenance: maintenanceLogs.length,
                fuel: fuelLogs.length,
                alerts: alerts.length,
            },
        });
    } catch (error) {
        console.error('Seed error:', error);
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        );
    }
}
